version: '2'
services:
  web:
    image: hello-world
    restart: always
  haproxy:
    image: haproxy
    restart: always
    links:
     - web
    ports:
     - '80:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock