version: '3.5'

services:

  replica1:
    container_name: replica1
    hostname: replica1
    image: hello-world
    restart: always

  replica2:
    container_name: replica2
    hostname: replica2
    image: hello-world
    restart: always
    depends_on:
      - replica1

  replica3:
    container_name: replica3
    hostname: replica3
    image: hello-world
    restart: always
    depends_on:
      - replica1

  lb:
    container_name: lb
    hostname: lb
    build: haproxy
    ports:
      - "5432:5432"
      - "8080:8080"
      - "8081:8081"
    links:
      - replica1
      - replica2
      - replica3
